### ISSUE TITLE
[BUG] No text on normal view of ground

### ISSUE THREAD

**Issue by AliM9130** [VATSIM-Saudi-Arabia/Saudi-vACC-Sector-File-Controller-Pack#12]
**Describe the bug**
when you zoom in you can see all the taxi lines texts and gates, but when you zoom out to fit it on your scope, doesn't show anything even the taxi lines which are important

**To Reproduce**
1. 2410/01
2. Jeddah CTR
3. None

**Expected behavior**
I was expecting to show all the taxi lines texts 
![Jeddah CTR expectation](https://github.com/user-attachments/assets/e50e6fa4-715e-4c6a-a9cc-78432c581376)

**Screenshots**
![Jeddah CTR new sector update](https://github.com/user-attachments/assets/dcb21094-eb54-48bf-81cb-775d9a98d01f)

**Desktop (please complete the following information):**
 - OS: 11 pro
 - Euroscope Version: v3.2cr2

**Additional context**

**Comment by Ismailhassan12** [comment]
Fixed. Will be implemented in AIRAC 2412
