### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by AliM9130** [VATSIM-Saudi-Arabia/Saudi-vACC-Sector-File-Controller-Pack#14]
**Describe the bug**
The Riyadh GMC needs to be facing north

**To Reproduce**
1. Latest 2413
2. Riyadh CTR
3. None

**Expected behavior**
The airport layout must face towards north. I have included pictures to interpret this issue.

**Screenshots**
I have attached pictures to represent the problem which needs to be fixed.
![riyadh gnd](https://github.com/user-attachments/assets/0a23e3fe-4262-49f0-9474-32e8beef8bb0)
![riyadh gmc layout navigraph](https://github.com/user-attachments/assets/1c14e6de-8021-462e-9b73-aa835983076e)

**Desktop (please complete the following information):**
 - OS: Windows 11 pro
 - Euroscope Version  v.3.2.2

**Additional context**
N/A

**Comment by Ismailhassan12** [comment]
Not a bug. You may change it to your liking via the display settings
